Module Help
    Sub ShowHelp()
        xtrace("")
        xtrace("---- " & AppName & " V" & AppVer & " -----------------------------------------")
        xtrace(" ", 0)
        xtrace(" Lets programs run in elevated mode or 'Run as Administrator' mode.", 0)
        xtrace(" Elevated processes do not inherit the process environment,", 0)
        xtrace(" also network drives may be missing, including the one you started from", 0)
        xtrace(" This program should be able to handle these issues", 0)
        xtrace(" ", 0)
        xtrace(" XElevate [Switches] <Executable> [Executable-Arguments]", 0)
        xtrace(" ", 0)
        xtrace(" XElevate Switches:", 0)
        xtrace("  -b  = Be Brief (Less information in the console)", 0)
        xtrace("  -c  = Transfer the environment complete", 0)
        xtrace("        Including: PROCESSOR_ARCHITECTURE, USERNAME ", 0)
        xtrace("  -d  = Set Debug In Elevated Environment", 0)
        xtrace("  -e  = Transfer the environment to the elevated process", 0)
        xtrace("  -h  = Help  (or --help or /h or /?)", 0)
        xtrace("  -i  = Disable Launch-File Indexing", 0)
        xtrace("  -k  = Starts the the %COMSPEC% environment variable value and", 0)
        xtrace("        executes <Executable> in it", 0)
        xtrace("  -m  = Start Minimized", 0)
        xtrace("  -p  = Pause before closing the elevated process", 0)
        xtrace("  -q  = Quet, does not show information in the console", 0)
        xtrace("  -r  = Redirect the output to the XElevate log file", 0)
        xtrace("  -v  = Verbose (Increase logged information)", 0)
        xtrace("  -q  = Be quiet", 1)
        xtrace("  -w  = Wait For Launched Process to finish", 0)
        xtrace("  -x  = Explicitly exit the process. ", 0)
        xtrace(" ", 0)
        xtrace(" --cv = Console verbose, Verbose towards the console", 0)
        xtrace(" --fmd= Fix Mapped network Drive if it is missing in the elevated process", 0)
        xtrace(" --w  = Set the wait time at the end of the elevated process", 0)
        xtrace("        --w=0 disables the wait, --w=" & UseWait.ToString & " is the defailt", 0)
        xtrace(" --help  = The same as -h", 0)
        xtrace(" --xhelp = extended help", 0)
        xtrace(" ", 0)
        xtrace(" Examples:", 0)
        xtrace(" Display Help:", 0)
        xtrace("   XElevate -h | more", 0)
        xtrace(" ", 0)
        xtrace(" Start an elevated command prompt that inherits the environment:", 0)
        xtrace("   XElevate -e cmd", 0)
        xtrace(" ", 0)
        xtrace(" Start a procedure with environment transfer, minimized and wait at the end", 0)
        xtrace("   XElevate -e -p -m C:\Temp\Test.bat", 0)
        xtrace("   XElevate -epm C:\Temp\Test.bat", 0)
        xtrace(" ", 0)
        xtrace(" Start a procedure with environment transfer and ", 0)
        xtrace(" Fix Mapped network Drive if it is missing in the elevated process", 0)
        xtrace(" Where -edrbwi are 6 separate single dash switches (See above)", 0)
        xtrace("   %SHARED%\XElevate -edrbwi --fmd %TA_MODULE_DIR%\Apply_Mods.bat", 0)
        xtrace(" ", 0)
        xtrace(" Created by Hans van Buitenen", 0)
        xtrace(" ", 0)
        xtrace("----------------------------------------------------------------------", 0)
        xtrace("", 0)
    End Sub

    Sub ShowXHelp()
        xtrace("Print Help")

        xtrace(" ", 0)
        xtrace("---- " & AppName & " V" & AppVer & " -----------------------------------------", 0)
        xtrace(" Lets programs run in elevated mode or 'Run as Administrator' mode.", 0)
        xtrace(" Elevated processes do not inherit the process environment,", 0)
        xtrace(" also network drives may be missing, including the one you started from", 0)
        xtrace(" This program should be able to handle these issues", 0)
        xtrace(" ", 0)
        xtrace(" XElevate [Switches] <Executable> [Executable-Arguments]", 0)
        xtrace(" ", 0)
        xtrace(" XElevate Switches:", 0)
        xtrace("  -b  = Be Brief (Less information in the console)", 0)
        xtrace("  -c  = Transfer the environment complete", 0)
        xtrace("        Including: PROCESSOR_ARCHITECTURE, USERNAME ", 0)
        xtrace("  -d  = Set Debug In Elevated Environment", 0)
        xtrace("  -e  = Transfer the environment to the elevated process", 0)
        xtrace("  -h  = Help  (or --help or /h or /?)", 0)
        xtrace("  -i  = Disable Launch-File Indexing", 0)
        xtrace("  -k  = Starts the the %COMSPEC% environment variable value and", 0)
        xtrace("        executes <Executable> in it", 0)
        xtrace("  -m  = Start Minimized", 0)
        xtrace("  -p  = Pause before closing the elevated process", 0)
        xtrace("  -q  = Quet, does not show information in the console", 0)
        xtrace("  -r  = Redirect the output to the XElevate log file", 0)
        xtrace("  -v  = Verbose (Increase logged information)", 0)
        xtrace("  -q  = Be quiet", 1)
        xtrace("  -w  = Wait For Launched Process to finish", 0)
        xtrace("  -x  = Explicitly exit the process. ", 0)
        xtrace(" ", 0)
        xtrace(" --cv  = Console verbose, Verbose towards the console", 0)
        xtrace(" --de  = Debug Exe, redirects the output to the log file. This is usefull if", 0)
        xtrace("         the process closes immidiately and you want to see the output.", 0)
        xtrace("         This only works properly if the called procedure exits! Also see -r. ", 0)
        xtrace(" --ep= = Explicitly set paramaters for the executed process", 0)
        xtrace(" --fmd = Fix Mapped network Drive if it is missing in the elevated process", 0)
        xtrace(" --w   = Set the wait time at the end of the elevated process", 0)
        xtrace("         --w=0 disables the wait, --w=" & UseWait.ToString & " is the defailt", 0)
        xtrace(" --help  = The same as -h", 0)
        xtrace(" --xhelp = extended help", 0)
        xtrace(" ", 0)
        xtrace(" Arguments:", 0)
        xtrace(" ", 0)
        xtrace(" ", 0)
        xtrace(" Environment:", 0)
        xtrace("  XElevate=TRUE       Is defined in the elevated process", 0)
        xtrace("  TA_DISABLE_FMD=TRUE Disable the --fmd functionality. This is a issue workaround", 0)
        xtrace("                      which is not yet completely adressed and confirmed.", 0)
        xtrace(" ", 0)
        xtrace(" Examples: ", 0)
        xtrace("   XElevate -i test.bat", 0)
        xtrace(" Both command below, --de and -r have more or less the same effect.", 0)
        xtrace("   XElevate -i --de %SystemRoot%\System32\cmd.exe --ep=""/c timeout /t 3""", 0)
        xtrace("   XElevate -ir %SystemRoot%\System32\cmd.exe", 0)
        xtrace(" ", 0)
        xtrace(" ", 0)
        xtrace(" ", 0)
        xtrace(" Display Help:", 0)
        xtrace("   XElevate -h | more", 0)
        xtrace(" ", 0)
        xtrace(" Start an elevated command prompt that inherits the environment:", 0)
        xtrace("   XElevate -e cmd", 0)
        xtrace(" ", 0)
        xtrace(" Start a procedure with environment transfer, minimized and wait at the end", 0)
        xtrace("   XElevate -e -p -m C:\Temp\Test.bat", 0)
        xtrace("   XElevate -epm C:\Temp\Test.bat", 0)
        xtrace(" ", 0)
        xtrace(" Start a procedure with environment transfer and ", 0)
        xtrace(" Fix Mapped network Drive if it is missing in the elevated process", 0)
        xtrace(" Where -edrbwi are 6 separate single dash switches (See above)", 0)
        xtrace("   %SHARED%\XElevate -edrbwi --fmd %TA_MODULE_DIR%\Apply_Mods.bat", 0)
        xtrace(" ", 0)
        xtrace(" Log file = " & LogFile, 0)
        xtrace(" Release and validate: P:\Dev\MDP\7.1.2a\XElevate", 0)
        xtrace(" Hans.van.Buitenen@philips.com", 0)
        xtrace(" https://github.com/Hans-van-B/XElevate/wiki", 0)
        xtrace(" ", 0)
        xtrace("----------------------------------------------------------------", 0)
        xtrace(" ", 0)

        wait(2)
    End Sub
End Module
