Module Util

    '---- Help  V2 ----------------------------------------------------------------
    Sub ShowHelpV2()
        xtrace("", 0)
        xtrace("---- XElevate Help ---------------------------------------------------", 0)
        xtrace(" ", 0)
        xtrace(" Extended elevate " & AppVersion, 0)
        xtrace(" Lets programs run in elevated mode or 'Run as Administrator' mode.", 0)
        xtrace(" Elevated processes do not inherit the process environment,", 0)
        xtrace(" also network drives may be missing, including the one you started from", 0)
        xtrace(" This program should be able to handle these issues", 0)
        xtrace(" ", 0)
        xtrace(" XElevate [param] <Executable> [Executable-Arguments]", 0)
        xtrace(" ", 0)
        xtrace(" XElevate paramaters:", 0)
        xtrace("  -b  = Be Brief (Less information in the console)", 0)
        xtrace("  -c  = Transfer the environment complete", 0)
        xtrace("        Including: PROCESSOR_ARCHITECTURE, USERNAME ", 0)
        xtrace("  -d  = Set Debug In Elevated Environment", 0)
        xtrace("  -e  = Transfer the environment to the elevated process", 0)
        xtrace("  -h  = Help  (or --help or /h or /?)", 0)
        xtrace("  -i  = Disable Launch-File Indexing", 0)
        xtrace("  -k  = Starts the the %COMSPEC% environment variable value and", 0)
        xtrace("        executes <Executable> in it", 0)
        xtrace("  -m  = Start Minimized", 0)
        xtrace("  -p  = Pause before closing the elevated process", 0)
        xtrace("  -q  = Quet, does not show information in the console", 0)
        xtrace("  -r  = Redirect the output to the XElevate log file", 0)
        xtrace("  -v  = Verbose (Increase logged information)", 0)
        xtrace("  -q  = Be quiet", 1)
        xtrace("  -w  = Wait For Launched Process to finish", 0)
        xtrace("  -x  = Explicitly exit the process. ", 0)
        xtrace(" ", 0)
        xtrace(" --cv = Console verbose, Verbose towards the console", 0)
        xtrace(" --fmd= Fix Mapped network Drive if it is missing in the elevated process", 0)
        xtrace(" --w  = Set the wait time at the end of the elevated process", 0)
        xtrace("        --w=0 disables the wait, --w=" & UseWait.ToString & " is the defailt", 0)
        xtrace(" ", 0)
        xtrace(" Examples:", 0)
        xtrace(" Display Help:", 0)
        xtrace("   XElevate -h | more", 0)
        xtrace(" ", 0)
        xtrace(" Start an elevated command prompt that inherits the environment:", 0)
        xtrace("   XElevate -e cmd", 0)
        xtrace(" ", 0)
        xtrace(" Start a procedure with environment transfer, minimized and wait at the end", 0)
        xtrace("   XElevate -e -p -m C:\Temp\Test.bat", 0)
        xtrace("   XElevate -epm C:\Temp\Test.bat", 0)
        xtrace(" ", 0)
        xtrace(" Start a procedure with environment transfer and ", 0)
        xtrace(" Fix Mapped network Drive if it is missing in the elevated process", 0)
        xtrace(" Where -edrbwi are 6 separate single dash switches (See above)", 0)
        xtrace("   %SHARED%\XElevate -edrbwi --fmd %TA_MODULE_DIR%\Apply_Mods.bat", 0)
        xtrace(" ", 0)
        xtrace("----------------------------------------------------------------------", 0)
        xtrace("", 0)
    End Sub

End Module
